/*

Reference: https://leetcode.com/problems/find-the-difference/

389. Find the Difference

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/
class Solution {
    public char findTheDifference(String s, String t) {
    
        char output = '0';
        Map<String, Integer> map = new HashMap<>();
        
        for(char c: t.toCharArray()) {
            if(map.containsKey(""+c))
                map.put("" + c, map.get(""+c) + 1);
            else
                map.put("" + c, 1);
        }
        
        for(char c: s.toCharArray()) {
            map.put("" + c, map.get(""+c) - 1);
        }
        
        for(Map.Entry<String, Integer> entry : map.entrySet()) {
            if(entry.getValue() == 1) {
                output = entry.getKey().toCharArray()[0];
                break;
            }
        }
        return output;
    }
}
